name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action: apply or destroy"
        required: true
        type: choice
        options:
          - apply
          - destroy
      region:
        description: "AWS Region (environment)"
        required: true
        type: choice
        options:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.region }}

    steps:

      - name: Checkout Terraform code repo
        uses: actions/checkout@v4
        with:
          repository: NurlanKurmanaliev/terraform-project-nexus
    

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
        
      - name: Write tfvars
        run: echo "${{ vars.TF_VARS_FILE }}" > terraform.tfvars

      - name: Generate a key pair
        run: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply or Destroy
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve -var-file=terraform.tfvars
